INSERT INTO vayahoteles.complementos_por_habitacion JSON '{"hotel_id":"hotel-vincci-de-santiago de compostela-55260dfb-0eab-4133-8ab4-0608ceaa5973","numero_habitacion":59660,"nombre":"tv","descripcion":"aut soluta laudantium"}';

INSERT INTO vayahoteles.complementos_por_habitacion JSON '{"hotel_id":"hotel-vincci-de-santiago de compostela-55260dfb-0eab-4133-8ab4-0608ceaa5973","numero_habitacion":59660,"nombre":"secador de pelo","descripcion":"ea non voluptatem"}';

