INSERT INTO vayahoteles.habitaciones_disponibles_por_fecha_y_hotel JSON '{"hotel_id":"hotel-courtyard-by-marriott-de-sevilla-b2f2f74e-efe9-4539-9528-614c58a38221","fecha":"2020-01-15T17:28:43.234Z","numero_habitacion":501,"es_disponible":true}';

INSERT INTO vayahoteles.habitaciones_disponibles_por_fecha_y_hotel JSON '{"hotel_id":"hotel-courtyard-by-marriott-de-sevilla-b2f2f74e-efe9-4539-9528-614c58a38221","fecha":"2020-01-16T17:28:43.234Z","numero_habitacion":502,"es_disponible":false}';

INSERT INTO vayahoteles.habitaciones_disponibles_por_fecha_y_hotel JSON '{"hotel_id":"hotel-courtyard-by-marriott-de-sevilla-b2f2f74e-efe9-4539-9528-614c58a38221","fecha":"2020-01-17T17:28:43.234Z","numero_habitacion":503,"es_disponible":true}';

INSERT INTO vayahoteles.habitaciones_disponibles_por_fecha_y_hotel JSON '{"hotel_id":"hotel-courtyard-by-marriott-de-sevilla-b2f2f74e-efe9-4539-9528-614c58a38221","fecha":"2020-01-18T17:28:43.234Z","numero_habitacion":504,"es_disponible":true}';
