INSERT INTO vayahoteles.hoteles_por_pdi JSON '{"nombre_pdi":"Residencia de San Filipo","hotel_id":"hotel-illunion-suites-de-jaen-73f80b71-1a06-465e-a648-2fe181718b7d","nombre":"Hotel Illunion Suites de Jaen","telefono":"901.637.922","direccion":"direccion de test"}';

INSERT INTO vayahoteles.hoteles_por_pdi JSON '{"nombre_pdi":"Residencia de San Filipo","hotel_id":"hotel-gran-via-apartamentos-de-cadiz-3bf90188-b05f-4195-bdad-13c42a8d78d5","nombre":"Hotel Gran Via Apartamentos de Cadiz","telefono":"948-105-542","direccion":"direccion de test"}';

INSERT INTO vayahoteles.hoteles_por_pdi JSON '{"nombre_pdi":"Fuente de San Filipo","hotel_id":"hotel-senator-de-santander-5cff9f98-130d-44b8-ae63-c1be1cd14887","nombre":"Hotel Senator de Santander","telefono":"950-856-545","direccion":"direccion de test"}';

INSERT INTO vayahoteles.hoteles_por_pdi JSON '{"nombre_pdi":"Fuente de San Filipo","hotel_id":"hotel-senator-de-santander-5cff9f98-130d-44b8-ae63-c1be1cd14887","nombre":"Hotel Senator de Santander","telefono":"950-856-545","direccion":"direccion de test"}';

