INSERT INTO vayahoteles.reservas_por_n JSON '{"n_confirmacion":"12345678","id_huesped":"1","n_habitacion":"500","id_hotel":"1234","fecha_entrada":"2020-01-18T17:28:43.234Z","fecha_salida":"2020-01-25T17:28:43.234Z"}';

INSERT INTO vayahoteles.reservas_por_n JSON '{"n_confirmacion":"98765432","id_huesped":"19","n_habitacion":"501","id_hotel":"1234","fecha_entrada":"2020-01-18T17:28:43.234Z","fecha_salida":"2020-01-27T17:28:43.234Z"}';

INSERT INTO vayahoteles.reservas_por_n JSON '{"n_confirmacion":"24681012","id_huesped":"abc","n_habitacion":"101","id_hotel":"1234","fecha_entrada":"2020-01-18T17:28:43.234Z","fecha_salida":"2020-01-27T17:28:43.234Z"}';
