{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"<div style=\\\"font-size: 200%; font-weight: bold; color: maroon;\\\">Machine Learning en Python: ejercicios de evaluación</div>\\n\",\n",
    "    \"<!-- Paulo Villegas, v. 1.3, 2023 -->\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">Por favor, escriba en la siguiente celda su nombre y apellidos</div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"**Bruno Urban Alfaro**:\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# Instrucciones\\n\",\n",
    "    \"\\n\",\n",
    "    \"La prueba consta de 4 preguntas, cada una con el mismo valor.\\n\",\n",
    "    \"\\n\",\n",
    "    \"1. Cargue los datos indicados en la sección de preparación\\n\",\n",
    "    \"2. Sobre esos datos, realice las operaciones indicadas en las secciones 1, 2 y 3. Introduzca el código necesario en la celda mencionada (si lo desea, puede repartirlo en varias celdas). En las preguntas 2 y 3 se pide además que explique los resultados obtenidos.\\n\",\n",
    "    \"3. Conteste a las preguntas de la sección 4 (son preguntas teóricas, no necesitan dataset ni código Python)\\n\",\n",
    "    \"4. Una vez terminados los ejercicios,\\n\",\n",
    "    \"   * descargue el _notebook_ **en formato `.ipynb`** (para ello use el menú _File_ -> _Download as_ -> _Notebook_ ),\\n\",\n",
    "    \"   * empaquételo dentro de un fichero ZIP (esto se hace porque algunos sistemas de entrega no tratan bien los ficheros `ipynb`)\\n\",\n",
    "    \"   * y entréguelo para ser evaluado.\\n\",\n",
    "    \"\\n\",\n",
    "    \"Entregue **solo** el _notebook_, no adjunte más ficheros (es decir, no añada el fichero `.csv` con los datos), y asegúrese de que está en formato notebook, no en HTML o PDF.\\n\",\n",
    "    \"\\n\",\n",
    "    \"# Preparación\\n\",\n",
    "    \"\\n\",\n",
    "    \"Ejecute las siguiente celdas para cargar el DataFrame; contiene datos de vuelos a Nueva York durante 2014. Es una muestra más reducida del mismo dataset usado en [el notebook de ejercicios de regresión](http://localhost:8008/notebooks/host/UNED/W2/4.3p%20Regresi%C3%B3n%20-%20ejercicios.ipynb). \"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import numpy as np\\n\",\n",
    "    \"import pandas as pd\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"flights = pd.read_csv( 'DATOS/flights14_sample.csv' )\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"La siguiente tabla muestra las columnas que tiene el DataFrame, y qué datos contienen:\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"|columna|contenido\\n\",\n",
    "    \"| :- | :------------- |\\n\",\n",
    "    \"|`year`|fecha del vuelo (año)\\n\",\n",
    "    \"|`month`|fecha del vuelo (mes)\\n\",\n",
    "    \"|`day`|fecha del vuelo (día)\\n\",\n",
    "    \"|`dep_time`|instante real de salida (HHMM)\\n\",\n",
    "    \"|`dep_delay`|retraso en salida (minutos)\\n\",\n",
    "    \"|`arr_time`|hora de llegada\\n\",\n",
    "    \"|`arr_delay`|retraso en llegada (minutos)\\n\",\n",
    "    \"|`cancelled`|vuelo cancelado\\n\",\n",
    "    \"|`carrier`|compañía\\n\",\n",
    "    \"|`tailnum`|número de avión\\n\",\n",
    "    \"|`flight`|número de vuelo\\n\",\n",
    "    \"|`origin`|aeropuerto de origen\\n\",\n",
    "    \"|`dest`|aeropuerto de destino\\n\",\n",
    "    \"|`air_time`|tiempo de vuelo (minutos)\\n\",\n",
    "    \"|`distance`|distancia recorrida (millas)\\n\",\n",
    "    \"|`hour`|hora prevista de salida\\n\",\n",
    "    \"|`min`|minuto previsto de salida\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# 1. Manipulación de datos\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"## 1.1 Retraso importante\\n\",\n",
    "    \"\\n\",\n",
    "    \"Vamos a definir _\\\"retraso importante\\\"_ como un **retraso en la llegada** de más de una hora.\\n\",\n",
    "    \"\\n\",\n",
    "    \"Añada una columna con el nombre \\\"`retraso_importante`\\\" al DataFrame. La columna debe tener un valor booleano: `True` si el vuelo ha tenido más de una hora de retraso _en la llegada_ y `False` en caso contrario\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div style='font-style: italic; color: #109010; margin-top: 1ex;'>Indicación: en Python los operadores de comparación (mayor, menor, etc) producen valores booleanos</div>\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\"> retraso importante = flights[flights['dep_delay'] > 30]   retraso importante = retraso importante.astype(bool) </div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"## 1.2 Retrasos por compañía\\n\",\n",
    "    \"\\n\",\n",
    "    \"* Cuente cuántos vuelos con \\\"retraso importante\\\" ha tenido cada compañía. \\n\",\n",
    "    \"\\n\",\n",
    "    \"* Ordene el resultado, obteniendo la lista de compañías ordenadas por su número de retrasos importantes, en orden decreciente (de forma que la que más ha tenido esté la primera)\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div style='font-style: italic; color: #109010; margin-top: 1ex;'>Indicación: utilice el <a href=\\\"http://pandas.pydata.org/pandas-docs/stable/groupby.html#groupby-aggregate\\\">agrupamiento + agregación</a> para DataFrames.<br/> En Python los valores booleanos se pueden sumar. En la suma <code>True</code> cuenta como 1 y <code>False</code> como 0.</div>\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">vuelos_con_retraso_por_compania = dataframe[dataframe['retraso_importante'] == True].groupby('carrier').size()  vuelos_con_retraso_por_compania = vuelos_con_retraso_por_compania.sort_values(ascending=False).reset_index() </div>\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"## 1.3 Porcentaje de retrasos \\n\",\n",
    "    \"\\n\",\n",
    "    \"Calcule el ratio de vuelos retrasados (vuelos con retraso >1h) de cada compañía. Es decir, para cada compañía, qué tanto por ciento (o tanto por uno, cualquiera de los dos vale) de sus vuelos han tenido retrasos de más de 1 h\\n\",\n",
    "    \"\\n\",\n",
    "    \"Obtenga la lista de compañías con sus ratios calculados, ordenados de mayor a menor ratio.\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">total_vuelos_por_compania = dataframe.groupby('carrier').size()  vuelos_retrasados_por_compania = dataframe[dataframe['retraso_importante'] == True].groupby('carrier').size()  ratio_vuelos_retrasados_por_compania = (vuelos_retrasados_por_compania / total_vuelos_por_compania) * 100  ratio_vuelos_retrasados_por_compania.sort_values(by=ratio_vuelos_retrasados_por_compania, ascending=False)  </div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# 2. Representación gráfica\\n\",\n",
    "    \"\\n\",\n",
    "    \"Represente en dos gráficas, cada una con una nube de puntos ( _scatter_ ):\\n\",\n",
    "    \"* El retraso en la llegada (minutos) como función de la distancia recorrida\\n\",\n",
    "    \"* El retraso en la llegada (minutos) como función del instante **real** de salida\\n\",\n",
    "    \"\\n\",\n",
    "    \"Si puede, coloque las dos gráficas una a la izquierda de la otra. Si no lo consigue, cree cada gráfica en una celda distinta del _notebook_\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div style='font-style: italic; color: #109010; margin-top: 1ex;'>Indicación: use el método <a href=\\\"http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html\\\">plot</a> de Pandas sobre el DataFrame</div>\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">ax1.scatter(df['distance'], df['arr_delay'])ax1.set_xlabel('Distancia recorrida (millas)') ax1.set_ylabel('Retraso en la llegada (minutos)')  ax1.set_title('Retraso en la llegada vs. Distancia recorrida') ax2.scatter(df['dep_time'], df['arr_delay']) ax2.set_xlabel('Instante real de salida')ax2.set_ylabel('Retraso en la llegada (minutos)') ax2.set_title('Retraso en la llegada vs. Instante real de salida') plt.subplots_adjust(wspace=0.3) plt.show()</div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">Describa a continuación las características más relevantes que observa en las gráficas representadas </div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"**Descripción:**\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# 3. Clasificación\\n\",\n",
    "    \"\\n\",\n",
    "    \"Vamos a tratar de entrenar un clasificador para que prediga si el vuelo tiene o no \\\"retraso importante\\\". Para ello:\\n\",\n",
    "    \"* Seleccione las columnas de _distancia recorrida_ y _hora real de salida_ como datos de entrada\\n\",\n",
    "    \"* Seleccione la columna creada de \\\"retraso importante\\\" como dato de salida\\n\",\n",
    "    \"* Separe los datos en conjunto de entrenamiento (75%) y conjunto de test (25%)\\n\",\n",
    "    \"* Instancie un clasificador de tipo `RandomForest`, configurado con 100 árboles,\\n\",\n",
    "    \"* Entrene usando el conjunto de entrenamiento creado\\n\",\n",
    "    \"* Calcule sobre el conjunto de test: la exactitud (`accuracy`) y la matriz de confusión (`confusion matrix`)\\n\",\n",
    "    \"* Comente los resultados\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">X = df[['distance', 'dep_time']] y = df['retraso_importante']  X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)</div>\"\n",
    "    \"<div> clf = RandomForestClassifier(n_estimators=100) clf.fit(X_train, y_train) y_pred = clf.predict(X_test) accuracy = accuracy_score(y_test, y_pred) confusion = confusion_matrix(y_test, y_pred)</div>\"\n",
    "    \n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">Comente aquí<ol><li>las características que observa en el modelo que ha entrenado<li>su opinión sobre los resultados que ha obtenido</ol></div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"**Explicación:**\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# 4. Preguntas teóricas\\n\",\n",
    "    \"\\n\",\n",
    "    \"Las siguientes preguntas son de contenido teórico, es decir, no precisan de realizar ningún tipo de código Python. Simplemente conteste a la pregunta en el recuadro marcado, razonando la respuesta\\n\",\n",
    "    \"\\n\",\n",
    "    \"## 4.1 Sobreentrenamiento\\n\",\n",
    "    \"\\n\",\n",
    "    \"Supongamos que tenemos un clasificador que usa un modelo con un nivel graduable de complejidad. Lo utilizamos para entrenar una clasificación con un dataset, y realizamos unos cuantos entrenamientos usando modelos con distinto grado de complejidad. Para evaluar medimos el error de clasificación tanto sobre el conjunto de entrenamiento como sobre el de test. El resultado es la siguiente gráfica que presenta los dos errores en función de la complejidad del modelo usado.\\n\",\n",
    "    \"\\n\",\n",
    "    \"<img src=\\\"IMG/ml-python-ejercicio.png\\\" style=\\\"width: 600px; padding: -100px;\\\"/>\\n\",\n",
    "    \"\\n\",\n",
    "    \"Se pregunta: \\n\",\n",
    "    \"1. A la vista de la gráfica, ¿está este clasificador sobreentrenando? \\n\",\n",
    "    \"2. ¿Qué tipo de comportamiento observa en cuanto al sesgo y/o varianza del modelo?\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">Si está sobreentrenado. El hecho de que la gráfica muestre que el error de entrenamiento y de test disminuye cuando aumenta la complejidad es un claro indicio. Lo que está ocurriendo es que está aprendiendo a memorizar datos en lugar de aprender sus patrones.</div>\"\n",
    "   ]\"<div> Según lo comentado, el modelo parece estar experimentando un bajo sesgo y una alta varianza.  </div>\"\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"**Respuesta**:\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"## 4.2 Tipo de aprendizaje \\n\",\n",
    "    \"\\n\",\n",
    "    \"Una empresa de turismo ha conseguido un dataset de estancias de familias en hoteles que contiene, para cada familia:\\n\",\n",
    "    \"* el número de miembros\\n\",\n",
    "    \"* el país de origen\\n\",\n",
    "    \"* la edad de los padres\\n\",\n",
    "    \"* el gasto total realizado durante la estancia\\n\",\n",
    "    \"\\n\",\n",
    "    \"La empresa pretende, usando ese dataset, obtener un modelo que le permita predecir el gasto total de la familia a partir del número de miembros, país de origen y edad de los padres. ¿Qué tipo y/o subtipo de aprendizaje va a llevar a cabo este modelo, de entre los vistos en la unidad 4.1? Explique su respuesta.\\n\",\n",
    "    \"\\n\",\n",
    "    \"<div class=\\\"alert alert-warning\\\" role=\\\"alert\\\" style=\\\"margin-top: 24pt; margin-bottom: 0pt;\\\">Según el enunciado, parece que el tipo de aprendizaje va a ser la regresión, ya que el gasto total de la familia durante una estancia de hotel es un valor numérico</div>\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"**Respuesta**:\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3 (ipykernel)\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.10.6\"\n",
    "  },\n",
    "  \"toc\": {\n",
    "   \"base_numbering\": 1,\n",
    "   \"nav_menu\": {},\n",
    "   \"number_sections\": false,\n",
    "   \"sideBar\": true,\n",
    "   \"skip_h1_title\": false,\n",
    "   \"title_cell\": \"Table of Contents\",\n",
    "   \"title_sidebar\": \"Contents\",\n",
    "   \"toc_cell\": false,\n",
    "   \"toc_position\": {},\n",
    "   \"toc_section_display\": true,\n",
    "   \"toc_window_display\": false\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 1\n",
    "}\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
